name: mobile_uas
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Bold.ttf
        - asset: assets/fonts/InriaSans-BoldItalic.ttf
        - asset: assets/fonts/InriaSans-Italic.ttf
        - asset: assets/fonts/InriaSans-Light.ttf
        - asset: assets/fonts/InriaSans-LightItalic.ttf
        - asset: assets/fonts/InriaSans-Regular.ttf